BibliotecaWebApplication/Models/Libro.cs
namespace BibliotecaWebApplication.Models
{
    public class Libro
    {
        public Guid LibroId { get; set; }
        public string ISBN { get; set; }
        public string Titulo { get; set; }
        public int NumeroPaginas { get; set; }
        public string Formato { get; set; }
        public string? Portada { get; set; }
        public string? Contraportada { get; set; }


        public int? PublicacionId { get; set; }
        public Publicacion Publicacion { get; set; }

        public Libro()
        {
            this.LibroId = Guid.NewGuid();
        }

        // Propiedades de Navegación
        public ICollection<AutorLibro> AutorLibros { get; set; } = new List<AutorLibro>();

    }

}

BibliotecaWebApplication/Controllers/AutoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BibliotecaWebApplication.Data;
using BibliotecaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaWebApplication.Controllers
{
    public class AutoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AutoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Autores
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Autores.ToListAsync());
        }

        // GET: Autores/Details/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var autor = await _context.Autores
                .Include(a => a.AutorLibros) // Incluye los libros asociados al autor
                .ThenInclude(al => al.Libro) // Incluye los detalles de los libros
                .FirstOrDefaultAsync(a => a.AutorId == id);

            var img = autor.Imagen;
            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }

        // GET: Autores/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Autores/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("AutorId,Nombres,Apellidos,Nacionalidad,Imagen")] Autor autor, IFormFile ImagenAutor)
        {
            //if (ModelState.IsValid)
            {
                //agregar la imagen
                if (ImagenAutor != null )
                {
                    var fileName = Path.GetFileName(ImagenAutor.FileName);
                    var filePath = Path.Combine("wwwroot/Imagenes/Autores", fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await ImagenAutor.CopyToAsync(stream);
                    }

                    autor.Imagen = "/Imagenes/Autores/" + fileName;
                }



                autor.AutorId = Guid.NewGuid();
                _context.Add(autor);
                await _context.SaveChangesAsync();

                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(new { success = true, autor });
                }

                return RedirectToAction(nameof(Index));
            }
            return View(autor);
        }



        // GET: Autores/Edit/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autores.FindAsync(id);
            if (autor == null)
            {
                return NotFound();
            }
            return View(autor);
        }

        // POST: Autores/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Edit(Guid id, [Bind("AutorId,Nombres,Apellidos,Nacionalidad,Imagen")] Autor autor, IFormFile ImagenAutor)
        {
            if (id != autor.AutorId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    if (ImagenAutor != null)
                    {
                        var fileName = Path.GetFileName(ImagenAutor.FileName);
                        var filePath = Path.Combine("wwwroot/Imagenes/Autores", fileName);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await ImagenAutor.CopyToAsync(stream);
                        }

                        autor.Imagen = "/Imagenes/Autores/" + fileName;  // Almacena la nueva URL de la foto
                    }

                    _context.Update(autor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutorExists(autor.AutorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autor);
        }

        // GET: Autores/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autores
                .FirstOrDefaultAsync(m => m.AutorId == id);
            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }

        // POST: Autores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var autor = await _context.Autores.FindAsync(id);
            if (autor != null)
            {
                if (autor != null)
                {
                    if (!string.IsNullOrEmpty(autor.Imagen))
                    {
                        var imagePath = Path.Combine("wwwroot", autor.Imagen);
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    _context.Autores.Remove(autor);
                }

                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Bibliotecario, Administrador")]
        private bool AutorExists(Guid id)
        {
            return _context.Autores.Any(e => e.AutorId == id);
        }
    }
}

BibliotecaWebApplication/Controllers/LibrosController.cs
using BibliotecaWebApplication.Data;
using BibliotecaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BibliotecaWebApplication.Controllers
{
    public class LibrosController : Controller
    {

        private readonly ApplicationDbContext _context;

        public LibrosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LibrosController
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Index()
        {
            var libros = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .ToListAsync();
            return View(libros);
        }

        // GET: LibrosController/Details/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros) // Incluye los autores asociados al libro
                .ThenInclude(al => al.Autor) // Incluye los detalles del autor
                .FirstOrDefaultAsync(m => m.LibroId == id);


            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: LibrosController/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {

            ViewBag.Autores = _context.Autores.ToList();

            return View();
        }

        // POST: LibrosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato,PublicacionId,Portada,Contraportada")] Libro libro, Guid[] selectedAutores, IFormFile portada, IFormFile contraportada)
        {
            //if (ModelState.IsValid)
            {
                    
                var publicacion = new Publicacion();
                _context.Publicaciones.Add(publicacion);
                await _context.SaveChangesAsync();

                libro.PublicacionId = publicacion.PublicacionId;
                libro.LibroId = Guid.NewGuid();

                // Guardar la imagen de la portada
                if (portada != null && portada.Length > 0)
                {
                    string portadaFileName = Path.GetFileName(portada.FileName);
                    string portadaPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Libros", portadaFileName);
                    using (var stream = new FileStream(portadaPath, FileMode.Create))
                    {
                        await portada.CopyToAsync(stream);
                    }
                    libro.Portada = portadaFileName;
                }

                if (contraportada != null && contraportada.Length > 0)
                {
                    string contraportadaFileName = Path.GetFileName(contraportada.FileName);
                    string contraportadaPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Libros", contraportadaFileName);
                    using (var stream = new FileStream(contraportadaPath, FileMode.Create))
                    {
                        await contraportada.CopyToAsync(stream);
                    }
                    libro.Contraportada = contraportadaFileName;
                }

                _context.Add(libro);
                await _context.SaveChangesAsync();

                if (selectedAutores != null)
                {
                    foreach (var autorId in selectedAutores)
                    {
                        var autorLibro = new AutorLibro
                        {
                            AutorId = autorId,
                            LibroId = libro.LibroId
                        };
                        _context.AutorLibros.Add(autorLibro);
                    }
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();

            return View(libro);
        }


        // GET: LibrosController/Edit/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.Publicacion)
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = libro.AutorLibros.Select(al => al.AutorId).ToList() ?? new List<Guid>();

            return View(libro);
        }


        // POST: LibrosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Edit(Guid? id, [Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato,Portada,Contraportada,PublicacionId")] Libro libro, Guid[] selectedAutores, IFormFile portada, IFormFile contraportada)
        {
            if (id != libro.LibroId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    var libroDb = await _context.Libros
                        .Include(l => l.Publicacion)
                        .FirstOrDefaultAsync(l => l.LibroId == id);

                    if (libroDb == null)
                    {
                        return NotFound();
                    }

                    libroDb.ISBN = libro.ISBN;
                    libroDb.Titulo = libro.Titulo;
                    libroDb.NumeroPaginas = libro.NumeroPaginas;
                    libroDb.Formato = libro.Formato;

                    // Actualizar la portada
                    if (portada != null && portada.Length > 0)
                    {
                        string portadaFileName = Path.GetFileName(portada.FileName);
                        string portadaPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Libros", portadaFileName);
                        using (var stream = new FileStream(portadaPath, FileMode.Create))
                        {
                            await portada.CopyToAsync(stream);
                        }
                        libroDb.Portada = portadaFileName; // Actualizar el nombre del archivo en el modelo
                    }

                    // Actualizar la contraportada
                    if (contraportada != null && contraportada.Length > 0)
                    {
                        string contraportadaFileName = Path.GetFileName(contraportada.FileName);
                        string contraportadaPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Libros", contraportadaFileName);
                        using (var stream = new FileStream(contraportadaPath, FileMode.Create))
                        {
                            await contraportada.CopyToAsync(stream);
                        }
                        libroDb.Contraportada = contraportadaFileName; // Actualizar el nombre del archivo en el modelo
                    }

                    _context.Update(libroDb);
                    await _context.SaveChangesAsync();

                    var existingAutorLibros = _context.AutorLibros.Where(al => al.LibroId == id);
                    _context.AutorLibros.RemoveRange(existingAutorLibros);

                    if (selectedAutores != null && selectedAutores.Any())
                    {
                        foreach (var autorId in selectedAutores)
                        {
                            var autorLibro = new AutorLibro
                            {
                                AutorId = autorId,
                                LibroId = libro.LibroId
                            };
                            _context.AutorLibros.Add(autorLibro);
                        }
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.LibroId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = selectedAutores != null ? selectedAutores.ToList() : new List<Guid>();
            return View(libro);
        }



        // GET: LibrosController/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }


        // POST: LibrosController/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

BibliotecaWebApplication/Views/Libros/Create.cshtml
@model BibliotecaWebApplication.Models.Libro

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroPaginas" class="control-label"></label>
                <input asp-for="NumeroPaginas" class="form-control" />
                <span asp-validation-for="NumeroPaginas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Formato" class="control-label"></label>
                <input asp-for="Formato" class="form-control" />
                <span asp-validation-for="Formato" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="Portada">Portada</label>
                <input type="file" class="form-control" name="portada" id="Portada" />
            </div>
            <div class="form-group">
                <label for="Contraportada">Contraportada</label>
                <input type="file" class="form-control" name="contraportada" id="Contraportada" />
            </div>



            <h4>Seleccionar Autor(es)</h4>
            <table id="dataTable" class="table">
                <thead>
                    <tr>
                        <th>Seleccionar</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Nacionalidad</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var autor in ViewBag.Autores)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="selectedAutores" value="@autor.AutorId" />
                            </td>
                            <td>@autor.Nombres</td>
                            <td>@autor.Apellidos</td>
                            <td>@autor.Nacionalidad</td>
                        </tr>
                    }
                </tbody>
            </table>

            <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#createAuthorModal">
                + Crear Autor
            </button>

            <div class="form-group mt-3">
                <input type="submit" value="&#43; Crear" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary mt-3">
        &#8592; Volver atrás
    </a>
</div>


<!-- Modal para crear un autor por medio de un popup -->
<div class="modal fade" id="createAuthorModal" tabindex="-1" role="dialog" aria-labelledby="createAuthorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createAuthorModalLabel">Crear Autor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="createAuthorForm" asp-controller="Autores" asp-action="Create" method="post">
                    <div class="form-group">
                        <label for="nombres">Nombres</label>
                        <input type="text" class="form-control" id="nombres" name="Nombres" required />
                    </div>
                    <div class="form-group">
                        <label for="apellidos">Apellidos</label>
                        <input type="text" class="form-control" id="apellidos" name="Apellidos" required />
                    </div>
                    <div class="form-group">
                        <label for="nacionalidad">Nacionalidad</label>
                        <input type="text" class="form-control" id="nacionalidad" name="Nacionalidad" required />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="button" class="btn btn-primary" id="saveAuthorButton">Guardar Autor</button>
                    </div>
                </form>
            </div>

            
        </div>
    </div>
</div>


@section Scripts {
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "language": {
                    "lengthMenu": "Mostrar _MENU_ entradas por página",
                    "zeroRecords": "No se encontraron resultados",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                    "infoEmpty": "Mostrando 0 a 0 de 0 entradas",
                    "infoFiltered": "(filtrado de _MAX_ entradas totales)",
                    "search": "Buscar:",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });

            $('#saveAuthorButton').click(function () {
                var form = $('#createAuthorForm');
                var formData = form.serialize(); // Serializa el formulario

                $.ajax({
                    url: form.attr('action'), // Usa la URL del formulario
                    type: 'POST',
                    data: formData,
                    success: function (result) {
                        if (result.success) {
                            var newAuthor = result.autor;
                            var newRow = '<tr>' +
                                '<td><input type="checkbox" name="selectedAutores" value="' + newAuthor.autorId + '" /></td>' +
                                '<td>' + newAuthor.nombres + '</td>' +
                                '<td>' + newAuthor.apellidos + '</td>' +
                                '<td>' + newAuthor.nacionalidad + '</td>' +
                                '</tr>';
                            $('#dataTable tbody').append(newRow);
                            $('#createAuthorModal').modal('hide'); // Cierra el modal
                            form[0].reset(); // Resetea el formulario
                        } else {
                            alert('Error al crear el autor: ' + result.message);
                        }
                    },
                    error: function (xhr, status, error) {
                        alert('Error al crear el autor: ' + error);
                    }
                });
            });
        });
    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BibliotecaWebApplication/Views/Libros/Delete.cshtml
@model BibliotecaWebApplication.Models.Libro

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>¿Estas seguro de que quieres eliminar los datos?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPaginas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroPaginas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Formato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Formato)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LibroId" />
        <button type="submit" class="btn btn-danger">
            <i class="fa fa-trash"></i> Borrar
        </button>
        <div>
            <a asp-action="Index" class="btn btn-secondary mt-3">
                &#8592; Volver atrás
            </a>
        </div>
    </form>

</div>

BibliotecaWebApplication/Views/Libros/Details.cshtml
@model BibliotecaWebApplication.Models.Libro

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Libro</h4>
    <br />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPaginas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroPaginas)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Formato)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Formato)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublicacionId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublicacionId)
        </dd>
        

        <dt class="col-sm-2">
            Portada
        </dt>
        <dd class="col-sm-10">
            @if (Model.Portada != null)
            {
                <img src="~/Imagenes/Libros/@Model.Portada" alt="Portada" class="img-thumbnail" style="max-width: 200px;" />
            }
            else
            {
                <p>No hay imagen de portada disponible.</p>
            }
        </dd>

        <dt class="col-sm-2">
            Contraportada
        </dt>
        <dd class="col-sm-10">
            @if (Model.Contraportada != null)
            {
                <img src="~/Imagenes/Libros/@Model.Contraportada" alt="Contraportada" class="img-thumbnail" style="max-width: 200px;" />
            }
            else
            {
                <p>No hay imagen de contraportada disponible.</p>
            }
        </dd>



    </dl>
</div>

<div>
    <h4>Autor(es):</h4>
    @if (Model.AutorLibros.Any())
    {
        <ul class="list-group list-group-flush">
            @foreach (var autorLibro in Model.AutorLibros)
            {
                <li class="list-group-item d-flex align-items-center">
                    <i class="fas fa-user fa-2x text-primary me-2" title="Autor"></i>
                    <span class="fw-semibold">
                        @autorLibro.Autor.Nombres @autorLibro.Autor.Apellidos
                    </span>
                </li>
            }
        </ul>
    }
    else
    {
        <p>Este libro no tiene autores asociados.</p>
    }
</div>


<div>
    <a asp-action="Edit" asp-route-id="@Model?.LibroId" class="btn btn-warning"><i class="bi bi-info-circle"></i> Editar</a>
</div>
<div>
    <a asp-action="Index" class="btn btn-secondary mt-3">
        &#8592; Volver atrás
    </a>
</div>