BibliotecaWebApplication/Controllers/LibrosController.cs
using BibliotecaWebApplication.Data;
using BibliotecaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BibliotecaWebApplication.Controllers
{
    public class LibrosController : Controller
    {

        private readonly ApplicationDbContext _context;

        public LibrosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LibrosController
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Index()
        {
            var libros = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .ToListAsync();
            return View(libros);
        }

        // GET: LibrosController/Details/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros) // Incluye los autores asociados al libro
                .ThenInclude(al => al.Autor) // Incluye los detalles del autor
                .FirstOrDefaultAsync(m => m.LibroId == id);


            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: LibrosController/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {

            ViewBag.Autores = _context.Autores.ToList();

            return View();
        }

        // POST: LibrosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato,PublicacionId,Portada,Contraportada")] Libro libro, Guid[] selectedAutores, IFormFile portada, IFormFile contraportada)
        {
            //if (ModelState.IsValid)
            {
                    
                var publicacion = new Publicacion();
                _context.Publicaciones.Add(publicacion);
                await _context.SaveChangesAsync();

                libro.PublicacionId = publicacion.PublicacionId;
                libro.LibroId = Guid.NewGuid();

                // Guardar la imagen de la portada
                if (portada != null && portada.Length > 0)
                {
                    string portadaFileName = Path.GetFileName(portada.FileName);
                    string portadaPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Libros", portadaFileName);
                    using (var stream = new FileStream(portadaPath, FileMode.Create))
                    {
                        await portada.CopyToAsync(stream);
                    }
                    libro.Portada = portadaFileName;
                }

                if (contraportada != null && contraportada.Length > 0)
                {
                    string contraportadaFileName = Path.GetFileName(contraportada.FileName);
                    string contraportadaPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Libros", contraportadaFileName);
                    using (var stream = new FileStream(contraportadaPath, FileMode.Create))
                    {
                        await contraportada.CopyToAsync(stream);
                    }
                    libro.Contraportada = contraportadaFileName;
                }

                _context.Add(libro);
                await _context.SaveChangesAsync();

                if (selectedAutores != null)
                {
                    foreach (var autorId in selectedAutores)
                    {
                        var autorLibro = new AutorLibro
                        {
                            AutorId = autorId,
                            LibroId = libro.LibroId
                        };
                        _context.AutorLibros.Add(autorLibro);
                    }
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();

            return View(libro);
        }


        // GET: LibrosController/Edit/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.Publicacion)
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = libro.AutorLibros.Select(al => al.AutorId).ToList() ?? new List<Guid>();

            return View(libro);
        }


        // POST: LibrosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Edit(Guid? id, [Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato,Portada,Contraportada,PublicacionId")] Libro libro, Guid[] selectedAutores, IFormFile portada, IFormFile contraportada)
        {
            if (id != libro.LibroId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    var libroDb = await _context.Libros
                        .Include(l => l.Publicacion)
                        .FirstOrDefaultAsync(l => l.LibroId == id);

                    if (libroDb == null)
                    {
                        return NotFound();
                    }

                    libroDb.ISBN = libro.ISBN;
                    libroDb.Titulo = libro.Titulo;
                    libroDb.NumeroPaginas = libro.NumeroPaginas;
                    libroDb.Formato = libro.Formato;

                    // Actualizar la portada
                    if (portada != null && portada.Length > 0)
                    {
                        string portadaFileName = Path.GetFileName(portada.FileName);
                        string portadaPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Libros", portadaFileName);
                        using (var stream = new FileStream(portadaPath, FileMode.Create))
                        {
                            await portada.CopyToAsync(stream);
                        }
                        libroDb.Portada = portadaFileName; // Actualizar el nombre del archivo en el modelo
                    }

                    // Actualizar la contraportada
                    if (contraportada != null && contraportada.Length > 0)
                    {
                        string contraportadaFileName = Path.GetFileName(contraportada.FileName);
                        string contraportadaPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagenes/Libros", contraportadaFileName);
                        using (var stream = new FileStream(contraportadaPath, FileMode.Create))
                        {
                            await contraportada.CopyToAsync(stream);
                        }
                        libroDb.Contraportada = contraportadaFileName; // Actualizar el nombre del archivo en el modelo
                    }

                    _context.Update(libroDb);
                    await _context.SaveChangesAsync();

                    var existingAutorLibros = _context.AutorLibros.Where(al => al.LibroId == id);
                    _context.AutorLibros.RemoveRange(existingAutorLibros);

                    if (selectedAutores != null && selectedAutores.Any())
                    {
                        foreach (var autorId in selectedAutores)
                        {
                            var autorLibro = new AutorLibro
                            {
                                AutorId = autorId,
                                LibroId = libro.LibroId
                            };
                            _context.AutorLibros.Add(autorLibro);
                        }
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.LibroId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = selectedAutores != null ? selectedAutores.ToList() : new List<Guid>();
            return View(libro);
        }



        // GET: LibrosController/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }


        // POST: LibrosController/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

BibliotecaWebApplication/Controllers/RolesController.cs
using BibliotecaWebApplication.Models.VeiewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BibliotecaWebApplication.Controllers
{
    [Authorize(Roles = "Root, Administrador")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }


        // GET: RolesController
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        // GET: RolesController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RolesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole { Name = model.Name };
                IdentityResult result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }


        // GET: RolesController/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            RoleViewModel model = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(model);
        }


        // POST: RolesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);
                if (role == null)
                {
                    return NotFound();
                }
                role.Name = model.Name;
                var result = await _roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }


        // POST: RolesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Root")]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View("Index");
        }


    }
}

BibliotecaWebApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BibliotecaWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BibliotecaWebApplication.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css " rol="Styleheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.3/css/dataTables.dataTables.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BibliotecaWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null && await UserManager.IsInRoleAsync(user, "Bibliotecario") || user != null && await UserManager.IsInRoleAsync(user, "Administrador"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Gestionar Publicaciones
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Autores" asp-action="Index">Autores</a></li>
                                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a></li>
                                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Revistas" asp-action="Index">Revistas</a></li>
                                    </ul>
                                </li>
                            }
                        }


                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null && await UserManager.IsInRoleAsync(user, "Bibliotecario") || user != null && await UserManager.IsInRoleAsync(user, "Administrador"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Gestionar Estanterias
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Estanterias" asp-action="Index">Estanterias</a></li>
                                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Estantes" asp-action="Index">Estantes</a></li>
                                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Ejemplares" asp-action="Index">Ejemplares</a></li>
                                    </ul>
                                </li>
                            }
                        }


                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null && await UserManager.IsInRoleAsync(user, "Root") || user != null && await UserManager.IsInRoleAsync(user, "Administrador"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Administrar Roles
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="UserRoles" asp-action="Index">Usuarios Roles</a></li>
                                    </ul>
                                </li>
                            }
                        }


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BibliotecaWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>